version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - '7000:7000'
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - external

networks:
  external:
    external:
      name: frontend-backend-net
