version: '3.8'

services:
  backend:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    ports:
      - "7000:7000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/ilearna?authSource=admin
    networks:
      - internal
      - external

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    driver: bridge
  external:
    external:
      name: frontend-backend-net