name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      env:
        MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
        MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}     
        envs: MONGO_INITDB_ROOT_USERNAME,MONGO_INITDB_ROOT_PASSWORD,MONGODB_URI
        script: |
            set -e
            cd /opt/backend
            echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env
            gh auth setup-git
            git checkout master
            git pull
            docker-compose down
            docker-compose up --build -d
            # Clean up dangling images
            docker rmi $(docker images -f "dangling=true" -q)
