name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}     
        script: |
            set -e
            cd /opt/backend
            echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env
            gh auth setup-git
            git checkout add-docker-config
            git pull
            docker-compose down
            docker-compose up --build -d